### ISSUE TITLE
Destination link

### ISSUE THREAD

**Issue by fabiosilvanet** [DalkMania/wp-jazz-hr-jobs#1]
Hi, @DalkMania 
Congrats for your plugin! :)
Maybe is not a issue.
But, any way to change the external Jazz Link?

For example, currently your plugin send Job Listing to link:
company.applytojob.com/apply/jobs/details/upbQ1o4d9f 
Which is not visually interesting like the custom page:
company.applytojob.com/apply/70sfwszLtY/Senior-PHP-Symfony

Thank you :-)

**Comment by DalkMania** [comment]
Hey @fabiosilvanet ... That's a great Idea. I'll see what I can do. I didn't know that was a thing honestly. Do you know what the `Senior-PHP-Symfony` part of the custom page is coming from? It is hopefully available through the API. If it is, this will be a simple change.

**Comment by fabiosilvanet** [comment]
Thank you, @DalkMania for your fast reply!
Any way to send you the original links in private, to check? :)

**Comment by DalkMania** [comment]
Sure. feel free to email me. And I'll take a quick look. and we can go from there? @fabiosilvanet

**Comment by DalkMania** [comment]
This has been added.
