### ISSUE TITLE
Sort order on the listings

### ISSUE THREAD

**Issue by skarr21** [DalkMania/wp-jazz-hr-jobs#2]
We are using your Jazz HR plugin (thank you, btw) and I'm wondering if there is a way to order the listings? For example, order by posted date asc or desc [jazz_hr_job_listings sort_by=date order=asc].

**Comment by DalkMania** [comment]
Great idea @skarr21 . I'll take a look over the weekend.

**Comment by DalkMania** [comment]
Hey @skarr21 . Sorry it took a while. But I added the sorting. 

Use `[jazz_hr_job_listings sort_by=date sort_order=asc]` to sort ascending. Replace with `desc` if you want to flip the direction. 

I hope this will work for you.

**Comment by skarr21** [comment]
Great! Thanks.
________________________________
