### ISSUE TITLE
Closed job showing in listing 

### ISSUE THREAD

**Issue by skarr21** [DalkMania/wp-jazz-hr-jobs#3]
We have jobs that are no longer active but still showing in the listings as Open Positions on https://www.bluetooth.com/sig-careers/

An example is [Software Development Engineer in Test II Contractor](https://bluetoothsiginc.applytojob.com/apply/YrKzvQoBrX).

This has been flagged in the "Exposure" section to not display on the Career Page, but it still shows. I then updated the status as "Drafting" and it is still showing. 

Thanks,
Steve
![jazz-exposure](https://user-images.githubusercontent.com/1273378/176745135-ae05c68d-e429-409f-b75c-58d780820619.png)
![jazz-open-status](https://user-images.githubusercontent.com/1273378/176745141-0b019d25-10b9-49c7-b36a-2ba312ff010e.png)

**Comment by skarr21** [comment]
Update - Now it isn't showing. Is the API slow in refreshing or something like that? 

Also, can we use the "Career Page" display toggle rather than "Open" or "Drafting" as what is used to show the listings?

**Comment by DalkMania** [comment]
Yeah there is a caching mechanism that will store the "result" for about an hour. Just to not hammer the API endpoint on every request. Glad it worked out in the end.
